### ISSUE TITLE
The "example" link is 404

### ISSUE THREAD

**Issue by tobireif** [pixijs/pixi-compressed-textures#1]
In the readme "This example shows" the link
https://github.com/pixijs/pixi-compressed-textures/blob/master/ivanpopelyshev.github.io/examples/index.html?s=textures&f=dds.js&title=DirectDrawSurface%20(DDS)&plugins=pixi-compressed-textures
is 404.

**Comment by ivanpopelyshev** [comment]
added https://, try now

**Comment by tobireif** [comment]
Works, thx
