### ISSUE TITLE
Pixi v6 Deprecated methods

### ISSUE THREAD

**Issue by radames** [pixijs/pixi-compressed-textures#37]
I'd be happy to submit a PR if that's the case.

`PIXI.systems.Resource` -->  `PIXI.ResourceDeprecated`
`PIXI.resources.TextureSystem`  -->  `PIXI.TextureSystemDeprecated`

![image](https://user-images.githubusercontent.com/102277/113367238-5cc36080-9310-11eb-9613-f34737ef402e.png)

**Comment by ivanpopelyshev** [comment]
the problem is, typings were changed. a lot. We cant compile it with TS anymore.

I can only modify resulting JS and publish it.

Alternatively, I can move it to new build system like `pixi-tilemap` was moved.

**Comment by ivanpopelyshev** [comment]
Also PixiJS v6 has compressed-textures internally, if you dont need my special kind of loader :)

https://github.com/pixijs/pixi.js/tree/dev/packages/compressed-textures

**Comment by radames** [comment]
hi @ivanpopelyshev, vey cool it's all integrated now!
I'm not sure if was able to port my code, I'm using `compressedTextures.loadFromArrayBuffer` and fetching `.basis` manually. I couldn't find similar API on v6 

~~~js
mainTexture = fetch(
  !darkMode
    ? await FileAttachment("final-100n-250-white-8192@1.basis").url()
    : await FileAttachment("final-100n-250-black-8192.basis").url()
)
  //   .arrayBuffer() // FileAttachment("final-basis-level-3.basis")
  .then(d => d.blob())
  .then(blob => blob.arrayBuffer())
  .then(array => PIXI.compressedTextures.loadFromArrayBuffer(array))
  .then(d => {
    const texture = new PIXI.BaseTexture(d);
    texture.scaleMode = PIXI.SCALE_MODES.NEAREST;
    return texture;
  })
~~~

**Comment by radames** [comment]
finally spent some time on this and found a way to use the loader functions directly  

~~~js
mainTexture = fetch(
  !darkMode
    ? await FileAttachment("final-100n-250-white-8192@1.basis").url()
    : await FileAttachment("final-100n-250-black-8192.basis").url()
)
  .then((d) => d.blob())
  .then((blob) => blob.arrayBuffer())
  .then((array) => PIXI.BasisLoader.transcodeAsync(array))
  .then((transcoded) => {
    const e = PIXI.BasisLoader.registerTextures("mainTexture", transcoded);
    return e.texture;
  })
  .then((texture) => {
    texture.scaleMode = PIXI.SCALE_MODES.NEAREST;
    return texture;
  })
~~~

here is the final example!

https://observablehq.com/@radames/blocks-embeddings
